amount-messages: 2
timer: 10
stick-level: 2
desligado: "desligando..."
start-message:
  - "        &e&l&nSnooker"
  - ""
  - "&fPara entrar digite: &7/sinuca"
  - "&fpremio: "
  - "&fjogadores participando"
  - ""
quit-message:
  -  "here"
  -  "here"
  -  "here"
  -  "here"
  -  "here"
