# Quantidade de Anuncios
amount-messages: 2
# Tempo Entre os Anuncios (EM SEGUNDOS)
timer: 10
# Nivel do encantamento do stick
stick-level: 2

not-online: "&cthe event is not currently online"
start-message:
  - "        &e&l&nSnooker"
  - ""
  - "&fPara entrar digite: &7/sinuca"
  - "&fpremio: "
  - "&fjogadores participando"
  - ""
quit-message:
  -  "here"
  -  "here"
  -  "here"
  -  "here"
  -  "here"
lack-of-player:
  - ""
  - ""
  - ""
  - ""